### ISSUE TITLE
How to filter out `.gitignore` with `python -m build --sdist`

### ISSUE THREAD

**Issue by jamesbraza** [pypa/setuptools-scm#1058]
I have a `pyproject.toml` like the below:

```toml
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_file = "src/package/version.py"
```

I noticed after running `python -m build --sdist` that the built `.tar.gz` contains version controlled files like `.gitignore` or folders like `.github`.

Reading the `setuptools` docs, it talks about `setuptools_scm` and including files: https://setuptools.pypa.io/en/stable/userguide/extension.html#adding-support-for-revision-control-systems

Is there some way to, within `pyproject.toml`, specify to `setuptools_scm` how to exclude files and folders? Or should one fall back onto `MANIFEST.in` for exclusions like that?
