### ISSUE TITLE
SETUPTOOLS_SCM_PRETEND_VERSION: parse node & distance

### ISSUE THREAD

**Issue by casperdcl** [pypa/setuptools-scm#1059]
`pyproject.toml` config:

```toml
[tool.setuptools_scm]
version_file = "src/version.py"
version_file_template = """
version = '{version}'
major = {version_tuple[0]}
minor = {version_tuple[1]}
patch = {version_tuple[2]}
commit_hash = '{scm_version.node}'
num_commit = {scm_version.distance}
"""
```

build:

```sh
SETUPTOOLS_SCM_PRETEND_VERSION="1.2.3.dev4+g1337beef" python -m build .
cat src/version.py
```

output:

```py
version = '1.2.3.dev4+g1337beef'
major = 1
minor = 2
patch = 3
commit_hash = 'None'
num_commit = 0
```

It's odd that `version` is correctly parsed into `version_tuple` but not `scm_version.node` nor `scm_version.distance`.

**Comment by RonnyPfannschmidt** [comment]
pretend_version currently has no scm metadata avaliable, its a string and not turned back into a scm_version - there should be warnings

**Comment by casperdcl** [comment]
ok, FYI I'm using this work-around:

```toml
[tool.setuptools_scm]
version_file_template = """
version = '{version}'
commit_hash = '{scm_version.node}'
distance = {scm_version.distance}
# work-around for https://github.com/pypa/setuptools_scm/issues/1059
if (commit_hash, distance) == ('None', 0):
    import re
    if (_v := re.search(r'\\.dev(\\d+)\\+(\\w+)', version)):
        distance, commit_hash = int(_v.group(1)), _v.group(2)
"""
```
