### ISSUE TITLE
missing `_version.py` after package installation

### ISSUE THREAD

**Issue by Borda** [pypa/setuptools-scm#1089]
Hello, I may have a silly question but could find a solution. We wanted to use this package version but for some reason, the generated `_version.py` file is missing the insulation. I have checked and when I build the package the file is there but after installing when I wrap the import with `try/expect` and list files in the root module the file is missing
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/.../sdk/__init__.py", line 47, in <module>
    raise RuntimeError(f"The version file is missing.\n {list_files}")
RuntimeError: The version file is missing.
 ['job', 'py.typed', 'api', 'utils', 'helpers.py', '__init__.py', '__pycache__', 'constants.py', 'cli']
```
so I have also added the file to `MANIFEST.in`
```
include sdk/_version.py
```
and mention it in package data - `pyproject.toml`
```toml
[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"sdk" = ["_version.py"]
```

**Comment by RonnyPfannschmidt** [comment]
Please include the configuration of setuptools_scm in the question 

Version files are a opt in

**Comment by Borda** [comment]
this is the configuration from `pyproject.toml`
```toml
[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8", "build"]
build-backend = "setuptools.build_meta"

[project]
...
dynamic = ["version"]

[project.scripts]
lightning = "sdk.cli.entrypoint:main_cli"

[tool.setuptools_scm]
version_file = "sdk/_version.py"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"sdk" = ["_version.py"]

[tool.setuptools.packages.find]
exclude = ["tests*", "examples*"]
```
