### ISSUE TITLE
After switching to setuptools_scm my package installed as version 0.0.0

### ISSUE THREAD

**Issue by polm** [pypa/setuptools-scm#386]
I tried switching to setuptools_scm for my package [fugashi](https://github.com/polm/fugashi) for v0.1.7 but when installing from pip the version is shown as 0.0.0. I saw the notes about conflicting settings in `setup.cfg` and such but I don't have any of that. In the source PKGINFO the version seems to be correctly set to 0.1.7. What did I do wrong?

[Here's a link](https://github.com/polm/fugashi/blob/9849a5a08d38e25e5bdfd317de3065589e335b49/setup.py) to setup.py at the 0.1.7 release. 

I saw several other issues about this in this repository but none of them seemed to be the same as this.

**Comment by RonnyPfannschmidt** [comment]
i think its related to a pip interaction issue i had trouble replicating before, i'm going to investigate if your particular issue fits that

if that's the case then #345 should eventually fix it after i managed to reproduce

**Comment by darrenburns** [comment]
I hit the same problem with a pyproject.toml like:

```toml
[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]

[tool.setuptools_scm]
write_to = "ward/_ward_version.py"
```

Running setuptools results in my package having version 0.0.0, even if I change the version_scheme.

It seemed to work fine when I used setuptools 41, and setup.py.
