### ISSUE TITLE
support defining a simple dict of scheme format strings for get_version  in pyproject.toml tool.setuptools_scm

### ISSUE THREAD

**Issue by graingert** [pypa/setuptools-scm#419]
for example:
```toml
# pyproject.toml

[tool.setuptools_scm.scheme]
no_distance_and_clean = "{tag}"
distance_and_clean = "{next_version}.dev{distance}+{scm_letter}{revision_hash}"
no_distance_and_not_clean = "{tag}+dYYYYMMDD"
distance_and_not_clean =  "{next_version}.dev{distance}+{scm_letter}{revision_hash}.dYYYYMMDD"
```

see also https://github.com/pypa/setuptools_scm/issues/418
