### ISSUE TITLE
python setup.py sdist only works with `pyproject.toml` when package is pre-installed in venv

### ISSUE THREAD

**Issue by jamesbraza** [pypa/setuptools-scm#487]
I am hitting what seems to be an edge when combining `python setup.py sdist`, `setup.py`, and `pyproject.toml`.

Here is my `pyproject.toml`:

```toml
[build-system]

requires = ["setuptools", "wheel", "setuptools_scm[toml]"]


[tool.setuptools_scm]

write_to = "desired/path/to/__version__.py"
root = ".."
relative_to = '__file__'
```

And my `venv` at the beginning:

```
Python==3.7.9
pip==20.2.4
setuptools==47.1.0
setuptools-scm==4.1.2
```

---

**Case 1**: didn't pre-install package

```bash
python setup.py sdist
```

Result: version of `0.0.0` (didn't work)

https://github.com/pypa/setuptools_scm/issues/386 seems related.

**Case 2**: pre-installed package

```bash
pip install -e .
python setup.py sdist
```

Result: version of `pkg-name-0.1.1.dev10+g28f91ce` (works)

**Case 3**: didn't install package + added config directly to `setup.py`

I add the `pyproject.toml` config section to `setup.py`'s `setup` function:

```python
setup(
    use_scm_version={
        "write_to": "desired/path/to/__version__.py",
        "root": "..",
        "relative_to": __file__,
    },
)
```

And do not have to pre-install the package:

```bash
python setup.py sdist
```

Result: version of `pkg-name-0.1.1.dev10+g28f91ce.d20201030` (works)

Note: this version has the date appended for some reason

---

**The Issue**

I would like to be able to use Case 1 above.  Unfortunately, it doesn't seem to work.  What might be the problem?  I have tried combing through the docs several times over, and haven't found any solutions.

In the meantime, I will be going with Case 2.
