### ISSUE TITLE
support distribution metadata substitution in write_to path

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/setuptools-scm#583]
unfortunately current packaging practices make it necessary to have the package name yet again in the src folder

practically this means people have to spell the package name in the write_to parameter

they should be able to do something like 
```toml
[tool.setuptools_scm]
write_to = "src/{toplevel}/_version.py"
```

_Originally suggested by @smarie in https://github.com/pypa/setuptools_scm/issues/582#issuecomment-862207084_

ideally in future src will directly map to the toplevel of a package

**Comment by smarie** [comment]
So efficient as always. Thanks @RonnyPfannschmidt !

**Comment by ssbarnea** [comment]
I really want to see this happening because it makes much harder to keep pyproject.toml synchronized across projects. Sadly TOML file format does not have support for generic substitutions like tox has. It only supports environment variables substitutions which is of no use for us, as we need to refer to refer to project.name and also to normalize the value as the name might be `foo-bar`, and it should translate to `foo_bar`.

On the other hand, I wonder if we could have another generic approach that does not need that and that will use the first module directory, mile `write_to = "{module_dir}/_version.py"`- module_dir should resolve to `./src/foo_bar`.

Any suggestions about approaches that could be implemented easily? -- We don't have to cover for multi-module care from start, as it a very uncommon layout.

## Update

I recently sorted another duplication in pyproject.toml by using via

```toml
[tool.ruff.lint.isort]
known-first-party = ["src"] # <-- used to be hardcoded name of the package
```

This makes me think that maybe using glob could be found suitable and also cover for the case where we have multiple python modules:

```toml
[tool.setuptools_scm]
write_to = "src/*/_version.py
```
