### ISSUE TITLE
Missing version file

### ISSUE THREAD

**Issue by henryiii** [pypa/setuptools-scm#606]
As of about an hour ago, projects are failing to write out a `write_to` version file. It's also not picking up the version properly, not sure why, I"m getting 0.0.0. No warning that I see in verbose mode.

I'm using (as always):

```toml
[build-system]
requires = ["wheel", "setuptools>=42", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/hist/version.py"
```

(Technically, ==6.1 to force the issue, locally it might pick up an older cached version)

Pretty much any install command seems to trigger it, `pip install -e .` does, but `pip install .` seems to too. It makes 0.0.0 and then my tests crash because `src/hist/version.py` wasn't produced.

Pinning `<6.1` fixes the issue, though I'm not looking forward to going through a dozen or more projects and adding the pin... edit: yanked, thanks!
