### ISSUE TITLE
Using only `pyproject.toml` for pip install results in 'project must contain version'

### ISSUE THREAD

**Issue by eivindjahren** [pypa/setuptools-scm#756]
I tried to switch my package github.com/equinor/ecl-data-io to use PEP 621 pyproject.toml (no setup.py) . However, it seems like there is no way to do that and use setuptools_scm. The following was my attempt to do so: 
```toml
[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "ecl-data-io"
description="A (lazy) parser and writer for the ecl output format."
readme = "README.md"
classifiers=[
    "Development Status :: 1 - Planning",
    "License :: OSI Approved :: GNU Lesser General Public License v3 or later (LGPLv3+)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
dependencies = ["numpy"]

[[project.authors]]
author = "Equinor"
email = "fg_sib-scout@equinor.com"

[[project.maintainers]]
name = "Eivind Jahren"
email = "ejah@equinor.com"

[project.license]
text = "LGPL-3.0"

[project.urls]
repository = "https://github.com/equinor/ecl-data-io"
documentation = "https://ecl-data-io.readthedocs.io/en/stable/"

[project.optional-dependencies]
doc = [
    "sphinx",
    "sphinx-rtd-theme",
]
dev = [
    "pytest",
    "hypothesis",
    "tox",
    "pre-commit"
]

[tool.setuptools_scm]
```

Running `pip install .` results in  `configuration error: project must contain ['version'] properties`.
