### ISSUE TITLE
SETUPTOOLS_SCM_PRETEND_VERSION requires "root" to be properly configured

### ISSUE THREAD

**Issue by jamesbraza** [pypa/setuptools-scm#771]
I have `$SETUPTOOLS_SCM_PRETEND_VERSION` set in a Docker container, and `python -m build --sdist` is not pulling in the version specified: I am getting a build of version 0.0.0.

I am wondering:
- What might be going wrong?
- What are ways to debug this?

---

**Set Up**

Here are the commands I am running with Python 3.7.15:

```bash
python -m pip install -U setuptools setuptools_scm build
export SETUPTOOLS_SCM_PRETEND_VERSION="0.1.0"
python -m build --sdist
```

No `setup.py` or `setup.cfg` are present.

<details><summary>pyproject.toml</summary>
<br>

```toml
[build-system]

# setuptools 62.6 is for dependencies being a requirements.txt file
# SEE: https://github.com/pypa/setuptools_scm/#pyprojecttoml-usage
requires = ["setuptools>=62.6", "setuptools_scm[toml]>=6.2"]

# SEE: https://peps.python.org/pep-0517/#source-trees
build-backend = "setuptools.build_meta"


[project]
# SEE: https://peps.python.org/pep-0621/#specification

# The name of the project
name = "foo"
description = "foo."
requires-python = ">=3.7"
license = {text = "foo"}
authors = [
    {name = "foo", email = "foo@email.com"}
]
urls = {repository = "https://github.com/foo"}

# Identify which metadata fields are dynamically computed during the build by
# either setuptools itself or the plugins installed via build-system.requires
dynamic = ["version", "dependencies"]


[tool.setuptools]
# SEE: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
# SEE: https://setuptools.pypa.io/en/latest/references/keywords.html

# Specifyies whether the project can be safely installed and run from a zip file
# SEE: https://github.com/python/mypy/issues/8802
zip-safe = false

# List of strings specifying the packages that setuptools will manipulate.
packages = ["foo"]


[tool.setuptools.dynamic]

# Directive for reading requirements.txt format
dependencies = {file = ["requirements.txt"]}
```

</details>

<details><summary>pip list</summary>
<br>

```
bleach             5.0.1
build              0.8.0
certifi            2022.9.24
cffi               1.15.1
charset-normalizer 2.1.1
commonmark         0.9.1
cryptography       38.0.2
docutils           0.19
idna               3.4
importlib-metadata 5.0.0
jaraco.classes     3.2.3
jeepney            0.8.0
keyring            23.9.3
more-itertools     8.14.0
packaging          21.3
pep517             0.13.0
pip                22.2.2
pkginfo            1.8.3
pycparser          2.21
Pygments           2.13.0
pyparsing          3.0.9
readme-renderer    37.2
requests           2.28.1
requests-toolbelt  0.10.0
rfc3986            2.0.0
rich               12.6.0
SecretStorage      3.3.3
setuptools         65.4.1
setuptools-scm     7.0.5
six                1.16.0
tomli              2.0.1
twine              4.0.1
typing_extensions  4.4.0
urllib3            1.26.12
webencodings       0.5.1
wheel              0.37.1
zipp               3.9.0
```

</details>

Note I have read this from the `README.rst`: https://github.com/pypa/setuptools_scm#usage-from-docker

I don't want to have to mount `.git`, hence why I am trying this workaround of `SETUPTOOLS_SCM_PRETEND_VERSION`.

**Comment by jamesbraza** [comment]
Okay I figured it out! My package was not at the repo root, it was one directory down, so I needed to add `root` to my `pyproject.toml`:

```toml
[tool.setuptools_scm]

root = ".."
```

I guess I assumed since `SETUPTOOLS_SCM_PRETEND_VERSION` is sort of a custom override ("pseudo version") on version, that the `root` being properly configured wouldn't matter.  This is not the case.

---

Do we think it's a bug that `SETUPTOOLS_SCM_PRETEND_VERSION` requires the repo root to be properly configured for Git?  I am thinking it should work regardless if `root` points at the repo root.
