### ISSUE TITLE
Deprecation warning when installing data files with setuptools_scm

### ISSUE THREAD

**Issue by anuppari** [pypa/setuptools-scm#814]
The [setuptools_scm readme](https://github.com/pypa/setuptools_scm#file-finders-hook-makes-most-of-manifestin-unnecessary) and [setuptools documentation](https://setuptools.pypa.io/en/latest/userguide/datafiles.html#include-package-data) suggest that setuptools automatically handles adding data/non-python files to the package. I see the following warning when I run `pip install -e .` in my package:

```
SetuptoolsDeprecationWarning:     Installing 'mypkg.data_folder' as data is deprecated, please list it in `packages`.
      !!


      ############################
      # Package would be ignored #
      ############################
      Python recognizes 'mypkg.data_folder' as an importable package,
      but it is not listed in the `packages` configuration of setuptools.

      'mypkg.data_folder' has been automatically added to the distribution only
      because it may contain data files, but this behavior is likely to change
      in future versions of setuptools (and therefore is considered deprecated).

      Please make sure that 'mypkg.data_folder' is included as a package by using
      the `packages` configuration field or the proper discovery methods
      (for example by using `find_namespace_packages(...)`/`find_namespace:`
      instead of `find_packages(...)`/`find:`).

      You can read more about "package discovery" and "data files" on setuptools
      documentation page.


  !!
```

My `pyproject.toml` has the following:

```toml

[build-system]
requires = ["setuptools>=61", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
name = "mypkg"
requires-python = ">=3.8"
dynamic = ["version"]
...
```

It seems that setuptools_scm is using a deprecated approach for adding the data files to the package?
