### ISSUE TITLE
Extra `toml` dependencies do not exist?

### ISSUE THREAD

**Issue by Saransh-cpp** [pypa/setuptools-scm#834]
The README says that I should install `setuptools_scm` as -
```toml
# pyproject.toml
[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
```

but while going through the `pyproject.toml` file of `setuptools_scm`, I found that the `toml` dependency list is empty -
https://github.com/pypa/setuptools_scm/blob/51b3566170be25582b5c3216a54b024caf3d431f/pyproject.toml#L54-L55

Am I missing something here or is installing `setuptools_scm` as `setuptools_scm` and `setuptools_scm[toml]` the same thing?
