### ISSUE TITLE
[RFC] customizing parse, annotate, and version/local scheme from pyproject.toml

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pypa/setuptools-scm#857]
in order to enable loading local files or passing extra configuration to scm parsing,
there should be a way to pass configuration for them in `pyproject.toml`

currently they are passed by name and do not take any arguments

in order to allow arguments they may be passed as dictionaries

the special keys `$name`, `$import`, `$from` and `$path`  will have meaning

```toml
old.version_scheme = "calver_by_date"
# will be short for 
new.version_scheme = {$name = "calver_by_date"}


# pass a date
new_with_args = {$name = "calver_by_date" , year="YYYY"} # the year arg was not added, serves as a example


#if name is not given, arguments to the default one will be assumed

new_with_default_name.version_scheme = {epoch="2"} # epoch is also not yet a supported argument, just serves as example


# when $from is a filename, use importlib to load that name
new_importlib.version_scheme = {$import = "my_version", $from: "src/my_version.py"}


# $path will be supported only as a last resort, build backend should enable importing , there may always be a warning about it

new_import_path.version_scheme = {$import "my_version, "$from: "my_version", $path: ["src"]}
```

to support customization/more detail,
parse/version_scheme_local_scheme will support passing a list of items, the first return value will be taken

also the system may eventually be deprecated for adding a system to specify build-system local entrypoints
