### ISSUE TITLE
Version file is not generated since version 8 on CI without any error

### ISSUE THREAD

**Issue by Czaki** [pypa/setuptools-scm#933]
Since `setuptools_scm` release 8 I have observed a test crash because the version file is not generated. 

```
   /tmp/tox/py311-PyQt5-all/lib/python3.11/site-packages/PartSeg/__init__.py:4: in <module>
      from PartSeg.version import version
  E   ModuleNotFoundError: No module named 'PartSeg.version'
``` 

When it is configured in pyproject.toml: https://github.com/4DNucleome/PartSeg/blob/bcaf0aad2e80edbf25e42859f8a0722074f0c68b/pyproject.toml#L1-L7

But when I pin `setuptools_scm` below 8 all problems disappear.

Here is log with `SETUPTOOLS_SCM_DEBUG` set to 1. 
https://github.com/4DNucleome/PartSeg/actions/runs/6273817081/job/17038040421?pr=1020

I cannot reproduce it locally. I do not have any idea how to debug this.

**Comment by RonnyPfannschmidt** [comment]
what version of tox is being used - its possible a pip upgrade of setuptools is needed, im not sure i can debug this one before monday

**Comment by RonnyPfannschmidt** [comment]
for extra details, please let the build package build a wheel with output and SETUPTOOL_SCM_DEBUG=true

**Comment by RonnyPfannschmidt** [comment]
@Czaki it seems like the shallow git checkout is trubling etuptools_scm

the .pkg workflow of tox i not producing any debug output either, so a lot is missing

**Comment by Czaki** [comment]
> what version of tox is being used

tox             4.11.3
setuptools      65.5.0


Build wheel and sdist (no version.py file) [package22.zip](https://github.com/pypa/setuptools_scm/files/12701685/package22.zip)

Logs from build package: [Build package.zip](https://github.com/pypa/setuptools_scm/files/12701697/Build.package.zip)

**Comment by Czaki** [comment]
> @Czaki it seems like the shallow git checkout is trubling etuptools_scm

The build linked above uses fetch depth 0 (all history) and still version file is not attached, even if the version is properly determined in file name.

But in other project we got such errors "ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any" on windows ci but not have yet enough information for separate report.

**Comment by Czaki** [comment]
I pass wrong variable: `SETUPTOOL_SCM_DEBUG` instead of `SETUPTOOLS_SCM_DEBUG` 

logs: [Build package.zip](https://github.com/pypa/setuptools_scm/files/12702254/Build.package.zip)
build output: [package22.zip](https://github.com/pypa/setuptools_scm/files/12702259/package22.zip)

EDIT. Also full repo history do not change the situation, and `version.py` file is absent.

**Comment by RonnyPfannschmidt** [comment]
the logs indicate lack of history (tus generating a wrong version) and indeed no logging of writing,

i'll need to debug this in detail

**Comment by Czaki** [comment]
Could I help somehow? Create log with full git history?

**Comment by RonnyPfannschmidt** [comment]
It seems i can replicate the issue using tox

More debugging is needed as to the cause

**Comment by RonnyPfannschmidt** [comment]
@Czaki i did a fresh local shallow clone and got version files correct, i suspect the tox setup is involved

**Comment by Czaki** [comment]
> @Czaki i did a fresh local shallow clone and got version files correct, i suspect the tox setup is involved

but I attach output from CI where I do only clone and call `python -m build` and file is missed. In this job there is no tox. 

```yaml
  build_package:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -U build

      - name: Build package
        run: |
          python -m build --sdist --wheel .
        env:
          SETUPTOOLS_SCM_DEBUG: true

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: package22
          path: dist
          retention-days: 5
```

Did you do shallow copy of this PR? 
If yes then you need to remove `<8` from `pyproject.toml` file the `setuptools_scm` constraints
